<a href="https://colab.research.google.com/github/ramgeethatamatam-rgb/Geetha/blob/main/numpy_scores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#..................................
#Task 1
#..................................
import numpy as np

np.random.seed(42)
scores = np.random.randint(50, 100, size = (5, 4))
print("scores :\n", scores)

#The score of the 3rd student in the 2nd subject
print ("Score of 3rd student in  the second subject:")
print(scores [2, 1])


#All scores of the last 2 students (all subjects)
print("All scores of the last 2 students (all subjects):")
print(scores [-2,1])

#All scores for the first 3 students in subjects 2 and 3 only
print("All scores for the first 3 students in subjects 2 and 3 only")
print(scores [:3, 1:3])





scores :
 [[88 78 64 92]
 [57 70 88 68]
 [72 60 60 73]
 [85 89 73 52]
 [71 51 73 93]]
Score of 3rd student in  the second subject:
60
All scores of the last 2 students (all subjects):
89
All scores for the first 3 students in subjects 2 and 3 only
[[78 64]
 [70 88]
 [60 60]]


In [18]:
# -------------------------------
# Task 2 — Broadcasting & Analysis
# -------------------------------


# 1 Column-wise mean (average per subject)
column_mean = np.round(scores.mean(axis=0), 2)
print("\n column-wise mean:", column_mean)

# 2️ Add curve using broadcasting'
curve = np.array([5, 3, 7, 2])
curved_scores = scores + curve
curved_scores = np.clip(curved_scores, None, 100)
print("\n Curved scores are :\n", curved_scores)


# 3️ Row-wise maximum (best subject per student)
row_max = curved_scores.max(axis=1)
print("\n Row wise max of best student per subject:", row_max)


 column-wise mean: [74.6 69.6 71.6 75.6]

 Curved scores are :
 [[93 81 71 94]
 [62 73 95 70]
 [77 63 67 75]
 [90 92 80 54]
 [76 54 80 95]]

 Row wise max of best student per subject: [94 95 77 92 95]


In [21]:
# ----------------------------
# Task 3 — Normalization & Identification
# ----------------------------

# Min-max normalization per row
row_min = curved_scores.min(axis=1, keepdims=True)
row_max = curved_scores.max(axis=1, keepdims=True)

normalized = (curved_scores - row_min) / (row_max - row_min)

print("\nNormalized Scores:\n", normalized)

# 1️ Index of single highest value in normalized array
max_index = np.unravel_index(np.argmax(normalized), normalized.shape)

print("\nHighest normalized value at:")
print("Student index:", max_index[0])
print("Subject index:", max_index[1])

# 2️ All curved scores strictly above 90
above_90 = curved_scores[curved_scores > 90]

print("\nScores above 90:", above_90)


Normalized Scores:
 [[0.95652174 0.43478261 0.         1.        ]
 [0.         0.33333333 1.         0.24242424]
 [1.         0.         0.28571429 0.85714286]
 [0.94736842 1.         0.68421053 0.        ]
 [0.53658537 0.         0.63414634 1.        ]]

Highest normalized value at:
Student index: 0
Subject index: 3

Scores above 90: [93 94 95 92 95]
